config/routes.rb
Impersona::Application.routes.draw do

  get '/server_arrays' => 'server_arrays#server_array', as: :server_arrays
  get '/get_array_inputs' => 'server_arrays#get_array_inputs', as: :get_array_inputs
  post '/post_array_inputs' => 'server_arrays#post_array_inputs', as: :post_array_inputs
  root 'server_arrays#server_array'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/server_arrays_controller.rb
class ServerArraysController < ApplicationController
  include ServerArraysHelper
  def server_array
  end

  def get_array_inputs
    @origin_name, @origin = server_array_inputs(params[:origin_array_id], params[:origin_account_id])
    @input_select_types = ['inherit', 'text', 'cred', 'env', 'key']
  end

  def post_array_inputs
    @dest_account_id = params[:dest_account_id]
    @dest_array_id = params[:dest_array_id]
    @inputs = params[:input_data]

    array_name = update_server_array_inputs(@dest_account_id, @dest_array_id, @inputs)
    flash[:notice] = "Inputs copied to #{array_name}"
    redirect_to server_arrays_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end

  def active_nav(actionName)
    'active' if params[:action] == actionName
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when :success
      'alert-success'
    when :error
      'alert-danger'
    when :alert
      'alert-block'
    when :notice
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/server_arrays_helper.rb
module ServerArraysHelper
  include Rightscale

  def rs_accounts
    account_hash = RIGHTSCALE_CONFIG['accounts']
    accounts = []
    account_hash.each do |account|
      accounts.push([account['name'].capitalize, account['id']])
    end
    return accounts
  end

  def server_array_inputs(array_id, account_id)
    Rightscale::ServerArray.get_inputs(array_id, account_id)
  end

  def update_server_array_inputs(account_id, array_id, inputs)
    Rightscale::ServerArray.update_inputs(array_id, account_id, inputs)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale.to_s %>'>
<head>
  <meta charset='utf-8'>
  <meta content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' name='viewport'>
  <title>
    <%= yield_or_default :title, controller.action_name.titlecase %>
  </title>
  <%= csrf_meta_tags %>
  <%= yield :head %>
<%= javascript_include_tag 'application' %>
<%= stylesheet_link_tag    "application", media: "all" %>

</head>
<body>
  <%= render 'shared/navbar' %>
  <div class='container' id='main-container'>
    <div class='content push'>
      <%= render partial: "shared/flash_messages", flash: flash %>
      <%= yield %>
    </div>
  </div>
  <div id='footer'>
    <div class='container'>
      <%= render 'shared/footer' %>
    </div>
  </div>
</body>
</html>

app/views/server_arrays/get_array_inputs.html.erb
<h3>Orig: <%= @origin_name %></h3>
<%= form_tag(post_array_inputs_path, :method=>'post', class: 'form-horizontal') do %>
  <div class='form-group'>
    <div class="col-sm-offset-3 col-sm-6">
      <span id="helpBlock" class="help-block">For credentials, if you want to copy the value of the credential, enter a new name for the credential in the new credential name box.</span>
    </div>
  </div>
  <% @origin.each do |input| %>
    <div class='form-group'>
      <label for="origin_array_id" class="col-sm-4 control-label"><%= input[:name] %>:</label>
      <div class="col-sm-2">
        <%= hidden_field_tag "input_data[][name]", input[:name] %>
        <%= select_tag "input_data[][type]", options_for_select(@input_select_types, selected: input[:type] ), class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <%= text_field_tag "input_data[][value]", input[:value], class: 'form-control' %>
      </div>
      <% if input[:type] == 'cred' %>
        <div class="col-sm-3">
          <%= text_field_tag "input_data[][new_cred_name]", '',class: 'form-control', placeholder: 'new credential name'  %>
        </div>
      <% end %>
    </div>
  <% end %>

  <h3>Destination</h3>
  <div class="form-group">
    <%= label_tag :dest_account_id, 'Destination Account', class: 'col-sm-3 control-label' %>
    <div class='col-sm-4'>
      <%= select_tag :dest_account_id, options_for_select(rs_accounts), { class: 'form-control account-id', prompt: 'Choose Account' } %>
    </div>
  </div>
  <div class='form-group'>
    <label for="dest_array_id" class="col-sm-3 control-label">Origin Array:</label>
    <div class="col-sm-6">
      <%= text_field_tag :dest_array_id, '', class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <div class="col-sm-offset-3 col-sm-6">
      <span id="helpBlock" class="help-block">In Rightscale, on the ServerArray Info page, look for the <strong>href</strong> line. It will look like <code>/api/server_arrays/302764003</code>. This array id is the last part of the href. You will enter <code>302764003</code></span>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-2">
      <%= submit_tag 'Copy Inputs', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/server_arrays/server_array.html.erb
<% title('Copy Server Array')%>
<h1>Copy Server Array Inputs</h1>
<div id='get_input_form'>
  <%= form_tag(get_array_inputs_path, :method=>'get', class: 'form-horizontal') do %>
    <h3>Origin</h3>

    <div class="form-group">
      <%= label_tag :origin_account_id, 'Origin Account', class: 'col-sm-3 control-label' %>
      <div class='col-sm-4'>
        <%= select_tag :origin_account_id, options_for_select(rs_accounts), { class: 'form-control account-id', prompt: 'Choose Account' } %>
      </div>
    </div>
    <div class='form-group'>
      <label for="origin_array_id" class="col-sm-3 control-label">Origin Array:</label>
      <div class="col-sm-6">
        <%= text_field_tag :origin_array_id, '', class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <div class="col-sm-offset-3 col-sm-6">
        <span id="helpBlock" class="help-block">In Rightscale, on the ServerArray Info page, look for the <strong>href</strong> line. It will look like <code>/api/server_arrays/302764003</code>. This array id is the last part of the href. You will enter <code>302764003</code></span>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-2">
        <%= submit_tag 'Get Inputs', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explination">
	<div class="alert alert-danger">
		<strong>The form contains <%= pluralize(object.errors.count, "error") %>:</strong>

		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
</div>

<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class='navbar navbar-default push'>
  <div class='container'>
    <div class='container'>
      <div class="navbar-header pull-right">
        <div class="navbar-text">Copy Server Array Inputs between RightScale Accounts</div>
      </div>
      <div class="navbar-header">
        <%= link_to 'Impersona', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li class="<%= active_nav('index') %>"><%= link_to 'Server Arrays', server_arrays_path, 'data-no-turbolink' => true %></li>
      </ul>
    </div>
  </div>
</div>

app/views/templates/_form.html.erb
<pre>Templates Form</pre>